stages:
  - .pre
  - build
  - test
  - deploy
  - .post

Pre-Build-Environment:
  stage: .pre
  image: arlenlt/android-cross-compiler:latest
  tags:
    - docker
  script:
    - echo $PATH
    - echo $PYENV_ROOT
    - echo $ANDROID_NDK
    - cmake --version

build_armv7:
  stage: build
  image: arlenlt/android-cross-compiler:latest
  tags:
    - docker
  script:
    - cmake --preset armv7
    - pushd armv7/build
    - cmake --build .
    - cmake --install .
    - popd
  artifacts:
    paths:
    - ./armv7/install
